# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50faf670b7314f099d4e971884b52469da830f6c197df7a359536481da805a9fe5a5dfcbdc7d03a8b506c11deec5b5e4a621f7773debf027d0b535d335bcae60

test:
  secret_key_base: 63a7b6ea73183cdede698299dc7ab661ba2f52c182d0e34d63dfc2cb81ab62bd2645d7487b7fc0734893f3de5e5972e05c794a23d28d2117a2e1442068bb773a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
